#!/bin/bash

PROJECT=`php -r "echo dirname(dirname(realpath('$0')));"`
PROJECT1=`php -r "echo dirname(realpath('$0'));"`
PROJECT2=`php -r "echo realpath('$0');"`
PROJECT3=`php -r "echo realpath('$0');"`
STAGED_FILES_CMD=`git diff --name-only --diff-filter=ACMR HEAD | grep "\.php$"`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo ${SFILES}
echo ${PROJECT}
echo ${PROJECT1}
echo ${PROJECT2}
echo ${PROJECT3}

echo "Checking PHP Lint..."


for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

# if [ "$FILES" != "" ]
# then

PHPSTAN="../../vendor/bin/phpstan"

if [ -f "$PHPSTAN" ]; then
    echo "Running PhpStan..."
    # ../../vendor/bin/phpstan analyze --no-progress-bar --no-error-table $FILES
	eval "$PHPSTAN analyze --level 0 --no-progress ./"
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        # echo "Run: './vendor/bin/ecs check $FILES --fix'"
        echo "Run: '$PHPSTAN analyze'"
        exit 1
    fi
fi

exit $?
